### ISSUE TITLE
Google Recaptcha failed to load error when trying to log in

### ISSUE THREAD

**Issue by shazron** [adobe/aio-lib-core-ims-oauth#2]
**Describe the bug**
After the Chromium browser loads, try to login. At a certain point, the browser closes and an error is logged in the console about failing to load a Google Recaptcha page.

**To Reproduce**
1. Use the appropriate `$ims` config settings
2. `aio ims:login`
3. Enter your email address, press Enter
4. Choose "Personal Account"
5. At this point the browser closes, and you see the error in the console log

**Expected behavior**
Successful login.

**Desktop (please complete the following information):**
 - OS: macOS 10.15
 - Browser [e.g. chrome, safari] Chromium
 - Version [e.g. 22] whatever was specified at sha https://github.com/adobe/aio-lib-core-ims-oauth/commit/2fe758d3547d282075cd308b5a9f8b6377ab18c9

**Additional context**
<details>
<summary>Log</summary>

```
 @adobe/aio-lib-core-ims-oauth/electron   > ERR: {"message":"Failed to load https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LeAzB4UAAAAAEQiceuQniNPhGMDXnt7ArGOyxHp&co=aHR0cHM6Ly9hdXRoLnNlcnZpY2VzLmFkb2JlLmNvbTo0NDM.&hl=en&v=75nbHAdFrusJCwoMVGTXoHoM&size=invisible&badge=inline&cb=8j7anhqs3e76\nReason:  (-3)"} +15s
  @adobe/aio-lib-core-ims-oauth/ims-oauth electronCallback(Error: Failed to load https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LeAzB4UAAAAAEQiceuQniNPhGMDXnt7ArGOyxHp&co=aHR0cHM6Ly9hdXRoLnNlcnZpY2VzLmFkb2JlLmNvbTo0NDM.&hl=en&v=75nbHAdFrusJCwoMVGTXoHoM&size=invisible&badge=inline&cb=8j7anhqs3e76 Reason:  (-3) at childProcess.execFile (/Users/shazron/Documents/git/adobe/aio-lib-core-ims-oauth/src/electron.js:40:34) at ChildProcess.exithandler (child_process.js:301:5) at ChildProcess.emit (events.js:198:13) at maybeClose (internal/child_process.js:982:16) at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5), undefined) +28ms
  @adobe/aio-lib-core-ims-oauth/ims-oauth   > Error: Failed to load https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LeAzB4UAAAAAEQiceuQniNPhGMDXnt7ArGOyxHp&co=aHR0cHM6Ly9hdXRoLnNlcnZpY2VzLmFkb2JlLmNvbTo0NDM.&hl=en&v=75nbHAdFrusJCwoMVGTXoHoM&size=invisible&badge=inline&cb=8j7anhqs3e76 Reason:  (-3) at childProcess.execFile (/Users/shazron/Documents/git/adobe/aio-lib-core-ims-oauth/src/electron.js:40:34) at ChildProcess.exithandler (child_process.js:301:5) at ChildProcess.emit (events.js:198:13) at maybeClose (internal/child_process.js:982:16) at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5) +1ms
  @adobe/aio-lib-core-ims-oauth/ims-oauth checkWebResult: Rejecting on error: Error: Failed to load https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LeAzB4UAAAAAEQiceuQniNPhGMDXnt7ArGOyxHp&co=aHR0cHM6Ly9hdXRoLnNlcnZpY2VzLmFkb2JlLmNvbTo0NDM.&hl=en&v=75nbHAdFrusJCwoMVGTXoHoM&size=invisible&badge=inline&cb=8j7anhqs3e76 Reason:  (-3) at childProcess.execFile (/Users/shazron/Documents/git/adobe/aio-lib-core-ims-oauth/src/electron.js:40:34) at ChildProcess.exithandler (child_process.js:301:5) at ChildProcess.emit (events.js:198:13) at maybeClose (internal/child_process.js:982:16) at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5) +74ms
  aio:ims:login Login Failure: Failed to load https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LeAzB4UAAAAAEQiceuQniNPhGMDXnt7ArGOyxHp&co=aHR0cHM6Ly9hdXRoLnNlcnZpY2VzLmFkb2JlLmNvbTo0NDM.&hl=en&v=75nbHAdFrusJCwoMVGTXoHoM&size=invisible&badge=inline&cb=8j7anhqs3e76
  aio:ims:login Reason:  (-3)
  aio:ims:login Error: Failed to load https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LeAzB4UAAAAAEQiceuQniNPhGMDXnt7ArGOyxHp&co=aHR0cHM6Ly9hdXRoLnNlcnZpY2VzLmFkb2JlLmNvbTo0NDM.&hl=en&v=75nbHAdFrusJCwoMVGTXoHoM&size=invisible&badge=inline&cb=8j7anhqs3e76
  aio:ims:login Reason:  (-3)
  aio:ims:login     at childProcess.execFile (/Users/shazron/Documents/git/adobe/aio-lib-core-ims-oauth/src/electron.js:40:34)
  aio:ims:login     at ChildProcess.exithandler (child_process.js:301:5)
  aio:ims:login     at ChildProcess.emit (events.js:198:13)
  aio:ims:login     at maybeClose (internal/child_process.js:982:16)
  aio:ims:login     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5) +16s
  @adobe/aio-lib-core-ims/context get current +15s
Error: Cannot get token for context 'oauth2_cli': Failed to load https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LeAzB4UAAAAAEQiceuQniNPhGMDXnt7ArGOyxHp&co=aHR0cHM6Ly9hdXRoLnNlcnZpY2VzLmFkb2JlLmNvbTo0NDM.&hl=en&v=75nbHAdFrusJCwoMVGTXoHoM&size=invisible&badge=inline&cb=8j7anhqs3e76
Reason:  (-3)
    at Object.error (/Users/shazron/Documents/git/adobe/aio-cli-plugin-ims/node_modules/@oclif/errors/lib/index.js:22:17)
    at LoginCommand.error (/Users/shazron/Documents/git/adobe/aio-cli-plugin-ims/node_modules/@oclif/command/lib/command.js:57:23)
    at LoginCommand.run (/Users/shazron/Documents/git/adobe/aio-cli-plugin-ims/src/commands/ims/login.js:44:18)
```
</details>

**Comment by fmeschbe** [comment]
Looks like there is a load for some invisible (?) re-captcha from Google which for some reason cannot be loaded which triggers a false positive in the `did-fail-load` handler.

Trying to fix this to only handle `did-fail-load` if the initial `authUrl` fails to load.

**Comment by fmeschbe** [comment]
Pushed commit 0b106a0. Feel free to test again, @shazron. Thanks.

**Comment by fmeschbe** [comment]
According to feedback, the issue seems to be solved. Therefore closing.
